version: "3"

tasks:
  create-cluster:
    desc: Create K3d cluster
    vars:
      CLUSTER_NAME:
        sh: echo "default-cluster-name"
    cmds:
      - bash hack/cluster/cluster-create.sh {{.CLUSTER_NAME}}

  destroy-cluster:
    desc: Destroy K3d cluster
    cmds:
      - bash hack/cluster-destroy.sh

  logs:
    desc: Show logs for a Helm release
    cmds:
      - kubectl logs -l app.kubernetes.io/instance={{.RELEASE_NAME}} --namespace {{.NAMESPACE}} --all-containers=true -f
