version: "3"

env:
  CLUSTER_NAME:
    sh: echo "dev-cluster"
  NAMESPACE: default
  RELEASE_NAME: jellyfin

tasks:
  create-cluster:
    desc: Create K3d cluster
    cmds:
      - bash hack/cluster/cluster-create.sh {{.CLUSTER_NAME}}

  destroy-cluster:
    desc: Destroy K3d cluster
    cmds:
      - bash hack/cluster/cluster-destroy.sh {{.CLUSTER_NAME}}

  logs:
    desc: Show logs for a Helm release
    cmds:
      - kubectl logs -l app.kubernetes.io/instance={{.RELEASE_NAME}} --namespace {{.NAMESPACE}} --all-containers=true -f

  helm-install:
    desc: Install Helm Chart
    cmds:
      - helm install {{.RELEASE_NAME}} charts/jellyfin --namespace {{.NAMESPACE}}

  helm-uninstall:
    desc: Uninstall Helm Chart
    cmds:
      - helm uninstall {{.RELEASE_NAME}} --namespace {{.NAMESPACE}}

  helm-test:
    desc: Run Helm Chart Tests
    cmds:
      - helm test {{.RELEASE_NAME}} --namespace {{.NAMESPACE}}

  helm-lint:
    desc: Lint Helm Chart
    cmds:
      - helm lint charts/jellyfin

  kubectl-create-namespace:
    desc: Create Kubernetes namespace
    cmds:
      - kubectl create namespace {{.NAMESPACE}} --dry-run=client -o yaml | kubectl apply -f -
