# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: 3

tasks:
  init:
    desc: Initialize pre-commit hooks
    cmds:
      - pre-commit install --install-hooks
    preconditions:
      - {msg: "pre-commit is not installed. Please install pre-commit.", sh: "command -v pre-commit",}

  update:
    desc: Update pre-commit dependencies
    cmds:
      - pre-commit autoupdate
    preconditions:
      - {msg: "pre-commit is not installed. Please install pre-commit.", sh: "command -v pre-commit",}

  run:
    desc: Run pre-commit
    cmds:
      - pre-commit run --all-files
    preconditions:
      - {msg: "pre-commit is not installed. Please install pre-commit.", sh: "command -v pre-commit",}

  base64-clipboard:
    desc: Base64 encode whatever is in the clipboard
    silent: true
    cmds:
      - pbpaste | base64 | pbcopy
